# The number of trials of a fuzzer-benchmark pair.
# We set the trials for 2 and 16.
trials: 2

# The amount of time in seconds that each trial is run for.
# 2 hours = 2 * 60 * 60 = 7200
max_total_time: 7200

# The location of the docker registry.
# FIXME: Support custom docker registry.
# See https://github.com/google/fuzzbench/issues/777
docker_registry: gcr.io/fuzzbench

# The local experiment folder that will store most of the experiment data.
# Please use an absolute path.
experiment_filestore: /home/ubuntu/experiment-data

# The local report folder where HTML reports and summary data will be stored.
# Please use an absolute path.
report_filestore: /home/ubuntu/report-data

# Flag that indicates this is a local experiment.
local_experiment: true
